name: POC Workflow

run-name: 'POC -- ${{github.ref_name}}'

on:
    workflow_dispatch:
        inputs:
            module:
                type: string
                description: Module
                required: true

env:
    MODULE_DIR: /home/runner/work/jpms-deps-poc/jpms-deps-poc/${{github.event.inputs.module}}
  

jobs:
  build-job:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
          - name: Checkout Code Repository
            uses: actions/checkout@v4
          - name: Setup Java
            uses: actions/setup-java@v4
            with:
              distribution: 'adopt'
              java-version: '21'

          - name: Change Directory
            run: cd ${{env.MODULE_DIR}}

          - name: Print Current Directory
            run: pwd
            working-directory: ${{env.MODULE_DIR}}

          - name: Maven Build
            if: github.ref == 'refs/heads/main'
            run: |
              mvn clean install \
                    -Dmaven.build.cache.enabled=false \
                    --batch-mode \
                    -e \
                    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn 
            working-directory: ${{env.MODULE_DIR}}       

          - name: Maven Build -- Feature Branch
            if: github.ref != 'refs/heads/main'
            run: |
              java --version
              mvn clean install \
                    -Dmaven.build.cache.enabled=false \
                    --batch-mode \
                    -e \
                    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn 